# Generated by Django 5.2.5 on 2025-08-11 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('lote', models.PositiveIntegerField()),
                ('min_veiculo', models.CharField(max_length=255, verbose_name='Veículo')),
                ('lance_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liberacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Liberação')),
                ('proporcao_fipe', models.CharField(blank=True, max_length=10, verbose_name='Proporção FIPE')),
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('renavam', models.CharField(max_length=11, unique=True)),
                ('ipva', models.CharField(blank=True, max_length=20)),
                ('chassi', models.CharField(max_length=17, unique=True)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ARREMATADO', 'Arrematado'), ('PAGO', 'Pagamento Confirmado'), ('RETIRADO', 'Retirado'), ('RETORNADO', 'Retornado com Multa')], default='DISPONIVEL', max_length=20)),
                ('comitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.comitente')),
            ],
            options={
                'ordering': ['lote'],
            },
        ),
    ]
