# Generated by Django 5.2.5 on 2025-08-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='chassi',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ipva',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='liberacao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='renavam',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='lance_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='proporcao_fipe',
            field=models.CharField(blank=True, max_length=20, verbose_name='Valor FIPE'),
        ),
    ]
