# Generated by Django 5.2.5 on 2025-08-11 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_veiculo_chassi_remove_veiculo_ipva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=255, verbose_name='Nome do Evento')),
                ('data_leilao_principal', models.DateField(verbose_name='Data Leilão Principal')),
                ('id_leilao_principal', models.CharField(max_length=50, verbose_name='ID Leilão Principal')),
                ('data_leilao_repasse', models.DateField(verbose_name='Data Leilão Repasse')),
                ('id_leilao_repasse', models.CharField(max_length=50, verbose_name='ID Leilão Repasse')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cliente', models.CharField(max_length=14, verbose_name='CPF do Cliente')),
                ('nome_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Cliente')),
                ('data_visita', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Visita')),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.leilao')),
            ],
        ),
    ]
