# Generated by Django 5.2.5 on 2025-08-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leilao_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arremate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cliente', models.CharField(max_length=14, verbose_name='CPF do Cliente')),
                ('nome_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Cliente')),
                ('valor_arremate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Arremate')),
                ('data_arremate', models.DateTimeField(auto_now_add=True, verbose_name='Data do Arremate')),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arremates', to='core.leilao')),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arremate', to='core.veiculo')),
            ],
        ),
    ]
