# Generated by Django 5.2.5 on 2025-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_arremate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ARREMATADO', 'Arrematado'), ('PAGAMENTO_CONFIRMADO', 'Pagamento Confirmado'), ('RETIRADO', 'Retirado'), ('RETORNADO', 'Retornado com Multa')], default='DISPONIVEL', max_length=25),
        ),
    ]
