# Generated by Django 5.2.5 on 2025-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_veiculo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arremate',
            name='cpf_cliente',
            field=models.CharField(max_length=18, verbose_name='CPF/CNPJ do Cliente'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='cpf_cliente',
            field=models.CharField(max_length=18, verbose_name='CPF/CNPJ do Cliente'),
        ),
    ]
