# Generated by Django 5.2.5 on 2025-08-14 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_arremate_cpf_cliente_alter_visita_cpf_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arremate',
            name='cpf_cliente',
            field=models.CharField(max_length=25, verbose_name='CPF/CNPJ do Cliente'),
        ),
        migrations.AlterField(
            model_name='arremate',
            name='data_arremate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Arremate'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='cpf_cliente',
            field=models.CharField(max_length=25, verbose_name='CPF/CNPJ do Cliente'),
        ),
    ]
